In [1]:
import numpy as np
import pandas as pd

# LOAD DATA

In [2]:
data_preprocessed = pd.read_csv(r"C:\Users\Bhaypreet\OneDrive\Pictures\IIT ROPAR\data_science_projects\Absenteeism\Absenteeism_Preprocess.csv")

In [3]:
data_preprocessed.head()

reason_G0  reason_G1  reason_G2  reason_G3  Day of the week  month_value  \
0          0          0          0          0                1            7   
1          0          0          0          0                1            7   
2          0          0          0          1                2            7   
3          1          0          0          0                3            7   
4          0          0          0          1                3            7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

# Creating targets ; Moderately and Highly absent

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(),1 ,0)


In [5]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets

In [7]:
data_preprocessed.head()

reason_G0  reason_G1  reason_G2  reason_G3  Day of the week  month_value  \
0          0          0          0          0                1            7   
1          0          0          0          0                1            7   
2          0          0          0          1                2            7   
3          1          0          0          0                3            7   
4          0          0          0          1                3            7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

# Balancing Targets

In [8]:
targets.sum()/targets.shape[0] 

np.float64(0.45571428571428574)

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

In [10]:
data_with_targets.head()

reason_G0  reason_G1  reason_G2  reason_G3  Day of the week  month_value  \
0          0          0          0          0                1            7   
1          0          0          0          0                1            7   
2          0          0          0          1                2            7   
3          1          0          0          0                3            7   
4          0          0          0          1                3            7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

# Input data

In [11]:
data_with_targets.shape

(700, 15)

In [12]:
input_data = data_with_targets.iloc[:,:-1]  

# STANDARDIZING DATA

In [13]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [14]:
absenteeism_scaler.fit(input_data)

StandardScaler()

In [15]:
standardized_inputs = absenteeism_scaler.transform(input_data) 

In [16]:
standardized_inputs.shape

(700, 14)

In [17]:
input_data.columns.values

array(['reason_G0', 'reason_G1', 'reason_G2', 'reason_G3',
       'Day of the week', 'month_value', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

# Train_Test_Split

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train ,x_test ,y_train ,y_test = train_test_split(standardized_inputs,targets , train_size = 0.8 , random_state = 20)

In [20]:
print(x_train.shape ,x_test.shape ,y_train.shape ,y_test.shape)

(560, 14) (140, 14) (560,) (140,)


# TRAINING THE MODEL : Logistic_Regression

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [22]:
reg = LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression()

In [23]:
x_pred = reg.predict(x_train)

In [24]:
print("Training_Accuracy :", accuracy_score(x_pred,y_train))

Training_Accuracy : 0.7517857142857143


# Manually checking the accuracy

In [25]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [26]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [27]:
np.sum(y_train==model_outputs)  

np.int64(421)

In [28]:
accuracy = 421/560
accuracy

0.7517857142857143

In [29]:
input_data.columns.values

array(['reason_G0', 'reason_G1', 'reason_G2', 'reason_G3',
       'Day of the week', 'month_value', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

In [30]:
col_names = (['reason_G0', 'reason_G1', 'reason_G2', 'reason_G3',
       'Day of the week', 'month_value', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets'])

In [31]:
reg.coef_

array([[ 1.04788613,  0.11624506,  0.87683314,  0.18801882, -0.05974196,
         0.13002781,  0.61618629,  0.03768526, -0.18414249, -0.03754129,
         0.28306871, -0.13196227,  0.3457179 , -0.34109656]])

## Summary Table

In [32]:
summary_table = pd.DataFrame (columns = ["Feature_name"] , data = col_names)

In [33]:
summary_table['Weights'] = np.transpose(reg.coef_)

In [34]:
summary_table

Feature_name   Weights
0                 reason_G0  1.047886
1                 reason_G1  0.116245
2                 reason_G2  0.876833
3                 reason_G3  0.188019
4           Day of the week -0.059742
5               month_value  0.130028
6    Transportation Expense  0.616186
7          Distance to Work  0.037685
8                       Age -0.184142
9   Daily Work Load Average -0.037541
10          Body Mass Index  0.283069
11                Education -0.131962
12                 Children  0.345718
13                     Pets -0.341097

In [35]:
summary_table.index = summary_table.index +1

In [36]:
summary_table.loc[0] = ['intercept_' , reg.intercept_[0]]

In [37]:
summary_table = summary_table.sort_index()

In [38]:
summary_table

Feature_name   Weights
0                intercept_ -0.184631
1                 reason_G0  1.047886
2                 reason_G1  0.116245
3                 reason_G2  0.876833
4                 reason_G3  0.188019
5           Day of the week -0.059742
6               month_value  0.130028
7    Transportation Expense  0.616186
8          Distance to Work  0.037685
9                       Age -0.184142
10  Daily Work Load Average -0.037541
11          Body Mass Index  0.283069
12                Education -0.131962
13                 Children  0.345718
14                     Pets -0.341097

# Interpreting the coef_

In [39]:
summary_table['Odds_ratio'] = np.exp(summary_table.Weights)
summary_table

Feature_name   Weights  Odds_ratio
0                intercept_ -0.184631    0.831411
1                 reason_G0  1.047886    2.851617
2                 reason_G1  0.116245    1.123271
3                 reason_G2  0.876833    2.403277
4                 reason_G3  0.188019    1.206856
5           Day of the week -0.059742    0.942008
6               month_value  0.130028    1.138860
7    Transportation Expense  0.616186    1.851852
8          Distance to Work  0.037685    1.038404
9                       Age -0.184142    0.831817
10  Daily Work Load Average -0.037541    0.963155
11          Body Mass Index  0.283069    1.327196
12                Education -0.131962    0.876374
13                 Children  0.345718    1.413004
14                     Pets -0.341097    0.710990

In [40]:
summary_table.sort_values('Odds_ratio',ascending = False)

Feature_name   Weights  Odds_ratio
1                 reason_G0  1.047886    2.851617
3                 reason_G2  0.876833    2.403277
7    Transportation Expense  0.616186    1.851852
13                 Children  0.345718    1.413004
11          Body Mass Index  0.283069    1.327196
4                 reason_G3  0.188019    1.206856
6               month_value  0.130028    1.138860
2                 reason_G1  0.116245    1.123271
8          Distance to Work  0.037685    1.038404
10  Daily Work Load Average -0.037541    0.963155
5           Day of the week -0.059742    0.942008
12                Education -0.131962    0.876374
9                       Age -0.184142    0.831817
0                intercept_ -0.184631    0.831411
14                     Pets -0.341097    0.710990

# Testing the model

In [41]:
predicted_proba = reg.predict_proba(x_test) 
predicted_proba

array([[0.77967493, 0.22032507],
       [0.69222427, 0.30777573],
       [0.51058933, 0.48941067],
       [0.82013817, 0.17986183],
       [0.06200778, 0.93799222],
       [0.25649954, 0.74350046],
       [0.29030948, 0.70969052],
       [0.08680622, 0.91319378],
       [0.84809647, 0.15190353],
       [0.70684248, 0.29315752],
       [0.48217096, 0.51782904],
       [0.18160613, 0.81839387],
       [0.04715936, 0.95284064],
       [0.72574631, 0.27425369],
       [0.23271289, 0.76728711],
       [0.65602982, 0.34397018],
       [0.5249181 , 0.4750819 ],
       [0.57645813, 0.42354187],
       [0.36872467, 0.63127533],
       [0.03165682, 0.96834318],
       [0.70719458, 0.29280542],
       [0.81410383, 0.18589617],
       [0.38682457, 0.61317543],
       [0.4061483 , 0.5938517 ],
       [0.18034497, 0.81965503],
       [0.83185857, 0.16814143],
       [0.4929773 , 0.5070227 ],
       [0.86906005, 0.13093995],
       [0.08742435, 0.91257565],
       [0.80791445, 0.19208555],
       [0.

In [42]:
predicted_proba.shape

(140, 2)

In [43]:
y_pred = reg.predict(x_test)

In [44]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Confusion Matrix:", confusion_matrix(y_test, y_pred))

Accuracy: 0.7214285714285714
              precision    recall  f1-score   support

           0       0.72      0.77      0.75        74
           1       0.72      0.67      0.69        66

    accuracy                           0.72       140
   macro avg       0.72      0.72      0.72       140
weighted avg       0.72      0.72      0.72       140

Confusion Matrix: [[57 17]
 [22 44]]


# SAVE THE MODEL

In [45]:
# import pickle

# with open('Logistic_model.pkl', 'wb') as f:
#     pickle.dump(reg, f)
